name: Kaiireply
version: ${version}
main: dev.kugge.kaiireply.Kaiireply
api-version: 1.19
authors: [kugge]
description: Simple reply plugin
commands:
  r:
    description: Kaiireply command
    usage: /<command>
    permission: kaiireply.reply